version: 2
jobs:
  build:
    docker:
    - image: circleci/openjdk:8
    steps:
    - checkout
    - restore_cache:
        key: v1-sbt-cache
    - run:
        name: Test
        command: sbt clean test scripted
    - save_cache:
        key: v1-sbt-cache
        paths:
        - "~/.ivy2/cache"
        - "~/.coursier/cache"
        - "~/.m2"
        - "~/.sbt"
